---
build:
  image: iron/go:dev
  commands:
    - go get
#    - go get -u github.com/Masterminds/glide
#    - glide install
    - go build
    - go test -v ./utils

  publish:
    docker:
      username: ${DOCKER_USERNAME}
      password: ${DOCKER_PASSWORD}
      email: ezanardo@onezerobinary.com
      repo: onezerobinary/db-box