---
compose:
  database:
    image: couchdb:latest
    environment:
      COUCHDB_USER: enrico
      COUCHDB_PASSWORD: "123456"
      COUCHDB_NAME: onezero-accounts
      COUCHDB_PORT_5984_TCP_ADDR: localhost
      COUCHDB_PORT_5984_TCP_PORT: "5984"
      DBNAME: onezero-accounts


pipeline:

#  build:
#    image: iron/go:dev
#    pull: true
#    commands:
#      - go get
#      - go get -u github.com/Masterminds/glide
#      - glide install
#      - go build
#      - go test -v ./utils

  build:
    image: iron/go:dev
    pull: true
    commands:
      - export PATH=$GOPATH/bin:$PATH
      - mkdir -p $GOPATH/src/github.com/onezerobinary/
      - cd ..
      - mv db-box $GOPATH/src/github.com/onezerobinary/.
      - cd $GOPATH/src/github.com/onezerobinary/db-box
      - go get -u github.com/Masterminds/glide
      - glide install
      - go build --tags nopkcs11
      - go test -v ./utils
#      - go test -v ./job --tags nopkcs11

#  cache:
#    mount:
#      - .git

#  publish:
  docker:
    image: docker
    storage_driver: overlay
    username: onezerobinary
    password: $$DOCKER_HUB_PASSWORD
    secrets: [ docker_hub_password ]
    email: ezanardo@onezerobinary.com
    repo: onezerobinary/db-box
    tag: latest
    when:
      branch: master

  rancher:
    image: peloton/drone-rancher
    url: http://139.162.131.149:8080/v1
    access_key: $$RANCHER_ACCESS_KEY
    secret_key: $$RANCHER_SECRET_KEY
    secrets: [ rancher_access_key, rancher_secret_key ]
    service: pulserescue/db-box
    docker_image: onezerobinary/db-box:latest
    timeout: 240
    when:
      branch: master
#
#  notify:
#    email:
#      host: smtp.webfaction.com
#      skip_verify: true
#      username: 10b_cicd
#      password: $$CICD_EMAIL_PASSWORD
#      from: cicd@onezerobinary.com
#      attachment: build-result.xml
#      recipients: [ ezanardo@onezerobinary.com, enrico.zanardo101@gmail.com ]