---
build:
  image: iron/go:dev
  commands:
    - go get --tags nopkcs11
#    - go get -t -v github.com/hyperledger/fabric/vendor/github.com/miekg/pkcs11
    - go get -u github.com/Masterminds/glide
    - glide install
    - go build --tags nopkcs11
    - go test -v ./utils
    - go test -v ./job --tags nopkcs11

compose:
  database:
    image: couchdb:latest
    environment:
      COUCHDB_USER: enrico
      COUCHDB_PASSWORD: 123456
      COUCHDB_NAME: onezero-accounts
      COUCHDB_PORT_5984_TCP_ADDR: localhost
      COUCHDB_PORT_5984_TCP_PORT: 5984
      DBNAME: onezero-accounts

cache:
  mount:
    - .git

publish:
  docker:
    storage_driver: overlay
    username: onezerobinary
    password: Ch120772Za
    email: ezanardo@onezerobinary.com
    repo: onezerobinary/db-box
    tag: latest
    when:
      branch: master

deploy:
  rancher:
    url: http://139.162.131.149:8080/v1
    access_key: 8EA7924C1F9A6C1223D4
    secret_key: kD79uqHL4tiyiUHFhPmEZrTvHcTtmJQFczDVzHny
    service: pulserescue/db-box
    docker_image: onezerobinary/db-box:latest
    when:
      branch: master

notify:
  email:
    host: smtp.webfaction.com
    skip_verify: true
    username: 10b_cicd
    password: D~F+K@D};1=4Se=
    from: cicd@onezerobinary.com
    attachment: build-result.xml
    recipients: [ ezanardo@onezerobinary.com, enrico.zanardo101@gmail.com ]