build:
  image: onezerobinary/db-box

  script:
    name: go get
    code: |
      go version
      go get -u github.com/Masterminds/glide
      glide install

  script:
    name: go test
    code: |
      go test -v ./utils