// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account/account.proto

/*
Package account is a generated protocol buffer package.

It is generated from these files:
	account/account.proto

It has these top-level messages:
	Empty
	Account
	Credentials
	Token
	Response
	Status
	UpdateStatus
	Accounts
	Email
*/
package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Account_Status int32

const (
	Account_NOTSET    Account_Status = 0
	Account_ENABLED   Account_Status = 1
	Account_DISABLED  Account_Status = 2
	Account_SUSPENDED Account_Status = 3
	Account_REVOKED   Account_Status = 4
)

var Account_Status_name = map[int32]string{
	0: "NOTSET",
	1: "ENABLED",
	2: "DISABLED",
	3: "SUSPENDED",
	4: "REVOKED",
}
var Account_Status_value = map[string]int32{
	"NOTSET":    0,
	"ENABLED":   1,
	"DISABLED":  2,
	"SUSPENDED": 3,
	"REVOKED":   4,
}

func (x Account_Status) String() string {
	return proto.EnumName(Account_Status_name, int32(x))
}
func (Account_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Status_Status int32

const (
	Status_NOTSET    Status_Status = 0
	Status_ENABLED   Status_Status = 1
	Status_DISABLED  Status_Status = 2
	Status_SUSPENDED Status_Status = 3
	Status_REVOKED   Status_Status = 4
)

var Status_Status_name = map[int32]string{
	0: "NOTSET",
	1: "ENABLED",
	2: "DISABLED",
	3: "SUSPENDED",
	4: "REVOKED",
}
var Status_Status_value = map[string]int32{
	"NOTSET":    0,
	"ENABLED":   1,
	"DISABLED":  2,
	"SUSPENDED": 3,
	"REVOKED":   4,
}

func (x Status_Status) String() string {
	return proto.EnumName(Status_Status_name, int32(x))
}
func (Status_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Account struct {
	Uuid       string         `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Username   string         `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Password   string         `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Token      *Token         `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
	Status     Account_Status `protobuf:"varint,5,opt,name=status,enum=account.Account_Status" json:"status,omitempty"`
	Type       string         `protobuf:"bytes,6,opt,name=type" json:"type,omitempty"`
	Created    string         `protobuf:"bytes,7,opt,name=created" json:"created,omitempty"`
	Expiration string         `protobuf:"bytes,8,opt,name=expiration" json:"expiration,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Account) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Account) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Account) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *Account) GetStatus() Account_Status {
	if m != nil {
		return m.Status
	}
	return Account_NOTSET
}

func (m *Account) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Account) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Account) GetExpiration() string {
	if m != nil {
		return m.Expiration
	}
	return ""
}

type Credentials struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Token    *Token `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
}

func (m *Credentials) Reset()                    { *m = Credentials{} }
func (m *Credentials) String() string            { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()               {}
func (*Credentials) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Credentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Credentials) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type Token struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Response struct {
	Code  int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Token *Token `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type Status struct {
	Status Status_Status `protobuf:"varint,1,opt,name=status,enum=account.Status_Status" json:"status,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Status) GetStatus() Status_Status {
	if m != nil {
		return m.Status
	}
	return Status_NOTSET
}

type UpdateStatus struct {
	Token  *Token  `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Status *Status `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *UpdateStatus) Reset()                    { *m = UpdateStatus{} }
func (m *UpdateStatus) String() string            { return proto.CompactTextString(m) }
func (*UpdateStatus) ProtoMessage()               {}
func (*UpdateStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateStatus) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *UpdateStatus) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type Accounts struct {
	Accounts []*Account `protobuf:"bytes,1,rep,name=accounts" json:"accounts,omitempty"`
}

func (m *Accounts) Reset()                    { *m = Accounts{} }
func (m *Accounts) String() string            { return proto.CompactTextString(m) }
func (*Accounts) ProtoMessage()               {}
func (*Accounts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Accounts) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type Email struct {
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
}

func (m *Email) Reset()                    { *m = Email{} }
func (m *Email) String() string            { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()               {}
func (*Email) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Email) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "account.Empty")
	proto.RegisterType((*Account)(nil), "account.Account")
	proto.RegisterType((*Credentials)(nil), "account.Credentials")
	proto.RegisterType((*Token)(nil), "account.Token")
	proto.RegisterType((*Response)(nil), "account.Response")
	proto.RegisterType((*Status)(nil), "account.Status")
	proto.RegisterType((*UpdateStatus)(nil), "account.UpdateStatus")
	proto.RegisterType((*Accounts)(nil), "account.Accounts")
	proto.RegisterType((*Email)(nil), "account.Email")
	proto.RegisterEnum("account.Account_Status", Account_Status_name, Account_Status_value)
	proto.RegisterEnum("account.Status_Status", Status_Status_name, Status_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AccountService service

type AccountServiceClient interface {
	// Create a new Account
	CreateAccount(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Response, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) CreateAccount(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/account.AccountService/CreateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AccountService service

type AccountServiceServer interface {
	// Create a new Account
	CreateAccount(context.Context, *Account) (*Response, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateAccount(ctx, req.(*Account))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _AccountService_CreateAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account/account.proto",
}

func init() { proto.RegisterFile("account/account.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x5d, 0xd2, 0xe6, 0x63, 0xb7, 0x5b, 0x09, 0x16, 0x1f, 0xd6, 0x24, 0x50, 0x15, 0x4d, 0xa2,
	0x0f, 0xa8, 0x93, 0x8a, 0x84, 0x78, 0x1d, 0x8b, 0x25, 0xd0, 0x50, 0x87, 0x92, 0x8e, 0x37, 0x1e,
	0x4c, 0xe2, 0x87, 0x68, 0x6b, 0x1c, 0xc5, 0x0e, 0xb0, 0x1f, 0xc0, 0x6f, 0xe3, 0x6f, 0x21, 0x7f,
	0xc4, 0x8c, 0xa2, 0xf6, 0x69, 0x4f, 0xf1, 0xb9, 0xf7, 0xc4, 0x3e, 0x3e, 0xe7, 0x1a, 0x9e, 0xd2,
	0xb2, 0xe4, 0x7d, 0x23, 0xcf, 0xec, 0x77, 0xd1, 0x76, 0x5c, 0x72, 0x14, 0x59, 0x98, 0x46, 0x10,
	0x90, 0x4d, 0x2b, 0xef, 0xd2, 0xdf, 0x3e, 0x44, 0xe7, 0xa6, 0x88, 0x10, 0x8c, 0xfb, 0xbe, 0xae,
	0xb0, 0x37, 0xf3, 0xe6, 0x87, 0xb9, 0x5e, 0xa3, 0x13, 0x88, 0x7b, 0xc1, 0xba, 0x86, 0x6e, 0x18,
	0xf6, 0x75, 0xdd, 0x61, 0xd5, 0x6b, 0xa9, 0x10, 0x3f, 0x78, 0x57, 0xe1, 0x91, 0xe9, 0x0d, 0x18,
	0x9d, 0x42, 0x20, 0xf9, 0x0d, 0x6b, 0xf0, 0x78, 0xe6, 0xcd, 0x27, 0xcb, 0xe9, 0x62, 0x10, 0xb2,
	0x56, 0xd5, 0xdc, 0x34, 0xd1, 0x19, 0x84, 0x42, 0x52, 0xd9, 0x0b, 0x1c, 0xcc, 0xbc, 0xf9, 0x74,
	0xf9, 0xdc, 0xd1, 0xac, 0xa6, 0x45, 0xa1, 0xdb, 0xb9, 0xa5, 0x29, 0x89, 0xf2, 0xae, 0x65, 0x38,
	0x34, 0x12, 0xd5, 0x1a, 0x61, 0x88, 0xca, 0x8e, 0x51, 0xc9, 0x2a, 0x1c, 0xe9, 0xf2, 0x00, 0xd1,
	0x4b, 0x00, 0xf6, 0xb3, 0xad, 0x3b, 0x2a, 0x6b, 0xde, 0xe0, 0x58, 0x37, 0xef, 0x55, 0xd2, 0x4b,
	0x08, 0xcd, 0xfe, 0x08, 0x20, 0x5c, 0x5d, 0xad, 0x0b, 0xb2, 0x4e, 0x0e, 0xd0, 0x04, 0x22, 0xb2,
	0x3a, 0x7f, 0xff, 0x89, 0x64, 0x89, 0x87, 0x8e, 0x20, 0xce, 0x3e, 0x16, 0x06, 0xf9, 0xe8, 0x18,
	0x0e, 0x8b, 0xeb, 0xe2, 0x33, 0x59, 0x65, 0x24, 0x4b, 0x46, 0x8a, 0x99, 0x93, 0x2f, 0x57, 0x97,
	0x24, 0x4b, 0xc6, 0xe9, 0x0d, 0x4c, 0x2e, 0x3a, 0x56, 0xb1, 0x46, 0xd6, 0xf4, 0x56, 0xfc, 0x63,
	0x9c, 0xb7, 0xc7, 0x38, 0x7f, 0x97, 0x71, 0xa3, 0x3d, 0xc6, 0xa5, 0x2f, 0x20, 0xd0, 0x18, 0x3d,
	0x19, 0xe8, 0xe6, 0x0c, 0xdb, 0xce, 0x20, 0xce, 0x99, 0x68, 0x79, 0x23, 0x98, 0xb2, 0xac, 0xe4,
	0x95, 0x11, 0x11, 0xe4, 0x7a, 0xfd, 0xf7, 0x10, 0x7f, 0xdf, 0x21, 0xbf, 0x3c, 0xe7, 0xcf, 0xc2,
	0x05, 0xe5, 0xe9, 0xa0, 0x9e, 0xb9, 0x3f, 0x0c, 0x61, 0x2b, 0xa7, 0x87, 0x75, 0xf6, 0x2b, 0x1c,
	0x5d, 0xb7, 0x15, 0x95, 0xcc, 0x6e, 0x79, 0x7a, 0xff, 0xce, 0x3b, 0x67, 0xeb, 0x95, 0x93, 0x6c,
	0x2e, 0xf9, 0x68, 0x4b, 0xb2, 0xd3, 0xfa, 0x0e, 0x62, 0x3b, 0x6d, 0x02, 0xbd, 0x86, 0xd8, 0xb2,
	0xd4, 0x4d, 0x47, 0xf3, 0xc9, 0x32, 0xd9, 0x1e, 0xc9, 0xdc, 0x31, 0x54, 0x0a, 0x64, 0x43, 0xeb,
	0x5b, 0x95, 0x02, 0x53, 0x8b, 0x21, 0x05, 0x0d, 0x96, 0x1f, 0x60, 0x6a, 0xff, 0x29, 0x58, 0xf7,
	0xbd, 0x2e, 0x19, 0x7a, 0x0b, 0xc7, 0x17, 0x7a, 0x36, 0x87, 0x27, 0xf7, 0xdf, 0xee, 0x27, 0x8f,
	0x5d, 0x65, 0x48, 0x30, 0x3d, 0xf8, 0x16, 0xea, 0xe7, 0xfb, 0xe6, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x8a, 0xa3, 0x10, 0x5e, 0xd7, 0x03, 0x00, 0x00,
}
